name: Run on large test instances (1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run algorithm on large test instances
        run: scripts/run_all.sh --pattern="0100-0" +router=greedy,flow,greedy+ls,flow+ls,sga

      - name: Process results
        run: mkdir multirun/results && uv run scripts/collect_logs.py multirun | uv run scripts/process_results.py > multirun/results/processed.xlsx

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: multirun
          include-hidden-files: true
