name: Run on small test instances

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run algorithm on small test instances
        run: scripts/run_all.sh 10-

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: multirun
          include-hidden-files: true

